---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: ambassador
spec:
  type: NodePort
  ports:
   - port: 80
     nodePort: 30303
     name: ambassador
  selector:
    service: ambassador
